version: "3.7"
   
services:
    db:
        image: postgres
        volumes:
        - postgres_data:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    backend:
        build: ./backend
        ports:
        - "8000:8000"
        depends_on:
        - db
        environment: 
        - DJANGO_SETTINGS_MODULE=backend.settings
        - SECRET_KEY=i@%!#v+@=^^e7960-)1$$)czkkb6un9np)n07j8i*pvj&rj_fdv
        networks:
        - app-net
    frontend:
        build: ./frontend
        ports:
        - "8080:8080"
        networks:
        - app-net

volumes:
    postgres_data:

networks:
    app-net: